---
- hosts: all
  vars:
    scala_version: 2.10.3
    sbt_version: 0.13.0
    java_provider: openjdk #  either openjdk or oracle 
  sudo: yes
  tasks: 
   ###########################################################################################################################################
   # For ORACLE JAVA 7, set java_provider variable to oracle.
   ###########################################################################################################################################
    - include: java-oracle-7.yaml
      when: java_provider == 'oracle'
    ##########################################################################################################################################
    # For OpenJDK, set java_provider variable to openjdk.
    ##########################################################################################################################################
    - name: Install OpenJDK 7
      apt: pkg=openjdk-7-jdk
      when: java_provider == 'openjdk'

    - name: Create Ansible Cache Directory
      file: path=/var/local/ansible-cache state=directory 

    - name: Download Scala {{scala_version}}
      get_url: dest=/var/local/ansible-cache/ url=http://www.scala-lang.org/files/archive/scala-{{scala_version}}.tgz

    - name: Extract Scala
      shell: tar xzf /var/local/ansible-cache/scala-{{scala_version}}.tgz -C /usr/local/share creates=/usr/local/share/scala-{{scala_version}}

    - name: Add Scala executable symlinks to path
      shell: for f in fsc scala scalac scaladoc scalap; do ln -s /usr/local/share/scala-{{scala_version}}/bin/$f /usr/local/bin/$f; done; creates=/usr/local/bin/scala   

    - name: Download SBT {{sbt_version}}
      get_url: dest=/var/local/ansible-cache url=http://repo.scala-sbt.org/scalasbt/sbt-native-packages/org/scala-sbt/sbt/{{sbt_version}}/sbt.tgz

    - name: Extract SBT
      shell: tar xzf /var/local/ansible-cache/sbt.tgz -C /usr/local/share creates=/usr/local/share/sbt

    - name: Add SBT executable symlinks to path
      shell: for f in sbt sbt-launch.jar; do ln -s /usr/local/share/sbt/bin/$f /usr/local/bin/$f; done; creates=/usr/local/bin/sbt

    - name: Update Scala environment variables
      sudo: no
      lineinfile: line="export SCALA_HOME=/usr/local/share/scala" dest="~/.bashrc" state=present regexp="export SCALA_HOME=/usr/local/share/scala"
